version: '3.8'

services:
  frontend:
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - "8501"
    environment:
      - DEEPSEEK_SERVICE_URL=http://deepseek_service:5000
      - STOCK_SERVICE_URL=http://stock_service:5001
      - PYTHONUNBUFFERED=1
      - ST_LOGGER_LEVEL=debug
      - VIRTUAL_HOST=app.deinedomain.com
      - LETSENCRYPT_HOST=app.deinedomain.com
      - LETSENCRYPT_EMAIL=dein@email.com
    depends_on:
      - deepseek_service
      - stock_service
    networks:
      - stockapp_net

  deepseek_service:
    build: ./deepseek
    volumes:
      - ./deepseek:/app
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - STOCK_SERVICE_URL=http://stock_service:5001
      - PYTHONUNBUFFERED=1
    expose:
      - "5000"
    networks:
      - stockapp_net

  stock_service:
    build: ./stock
    volumes:
      - ./stock:/app
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "5001"
    networks:
      - stockapp_net

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - stockapp_net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=dein@email.com
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - stockapp_net

networks:
  stockapp_net:
    driver: bridge

volumes:
  certs:
  vhost:
  html:
